ALTER TABLE clientes
  ADD COLUMN IF NOT EXISTS latitud DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS longitud DECIMAL(10,7),
  ADD COLUMN IF NOT EXISTS horario_atencion VARCHAR(100),
  ADD COLUMN IF NOT EXISTS horario_entrega VARCHAR(100),
  ADD COLUMN IF NOT EXISTS vendedor_id INTEGER REFERENCES usuarios(id),
  ADD COLUMN IF NOT EXISTS vendedor_nombre VARCHAR(100);
